name: umake test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        version: "0.5.29"
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: Install umake
      shell: bash -l {0}
      run : |
        uv sync --all-extras --dev
        uv pip install .
        uv pip install pytest
    - name: Test
      shell: bash -l {0}
      run: |
        uv run python -m pytest umake/tests/
        umake --supports docx pdf

